blog/blog/urls.py
from django.urls import  include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myblog/', include('myblog.urls', namespace='myblog')),
    path('super/', include('super.urls', namespace='super')),
]

blog/myblog/urls.py
from django.urls import path

from myblog import views

urlpatterns = [
    path('about', views.about, name='about'),
    path('gbook/', views.gbook, name='gbook'),
    path('index/', views.index, name='index'),
    path('info/', views.info, name='info'),
    path('infopic/', views.infopic, name='infopic'),
    path('list/', views.list, name='list'),
    path('column', views.column, name='column'),

]

blog/super/urls.py
from django.conf.urls import url
from django.urls import path

from super import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('index/', views.index, name='index'),
    path('logout/', views.logout, name='logout'),
    path('article/', views.article, name='article'),
    path('add_article/', views.add_article, name='add_article'),
    path('category/', views.category, name='category'),
    path('update_category/', views.update_category, name='update_category'),
    path('del_category/', views.del_category, name='del_category'),
    path('del_article/', views.del_article, name='del_article'),
    path('update_article/', views.update_article, name='update_article'),
]

blog/templates/web/about.html
{% extends 'web/base.html' %}

{% block css %}
    <link href="/static/web/css/base.css" rel="stylesheet">
    <link href="/static/web/css/index.css" rel="stylesheet">
    <link href="/static/web/css/m.css" rel="stylesheet">
{% endblock %}

{% block js %}
    <script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/web/js/hc-sticky.js"></script>
    <script type="text/javascript" src="/static/web/js/comm.js"></script>
    <!--[if lt IE 9]>
    <script src="/static/web/js/modernizr.js"></script>
    <![endif]-->
{% endblock %}



{% block aside %}

  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
        <i><img src="/static/web/images/4.jpg"></i>
        <p><b>Deathfeeling</b>，一个80后草根站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        <li><a href=""><img src="/static/web/images/7.jpg"></a></li>
        <li><a href=""><img src="/static/web/images/8.jpg"></a></li>
        <li><a href=""><img src="/static/web/images/9.jpg"></a></li>
        <li><a href=""><img src="/static/web/images/10.jpg"></a></li>
        <li><a href=""><img src="/static/web/images/11.jpg"></a></li>
        <li><a href=""><img src="/static/web/images/12.jpg"></a></li>
      </ul>
    </div>
    <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
          {% for column in columns %}
            <li><a href="{% url 'myblog:column' %}/?id={{ column.id }}">{{ column.name }}</a></li>
          {% endfor %}
        </ul>
    </div>

    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/web/images/wx.jpg">
      </ul>
    </div>
  </aside>
{% endblock %}


{% block main %}
  <main class="r_box">
     <div class="about">
      <p>Deathfeeling，一个80后草根站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。我入行早，大家也亲切的叫我&ldquo;青姐&rdquo;。<br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="/static/web/images/8.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来,12345678(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
           <br />
            SEO奋斗了将近两年时间，个人博客网站百度排名也从之前的30页后，排到了第一页。期间有很多的不容易，但是都没有放弃过。入了这一行，就深深的喜欢上它。我喜欢一句话&ldquo;冥冥中该来则来，无处可逃&rdquo;。<br />
            <br />
    <img src="/static/web/images/11.jpg">        近几年我也发现个人博客排前几页的也有很多是我做过的模板，感谢各位站长的欣赏，我仔细看过他们的网站。他们在我原模板的基础上有修改，而且他们做的原创内容都是值得一读的。有时候甚至排名都超过了我个人博客网站的排名。<br />
            <br />
            现在很多人向我请教如何做好SEO，我想说的是，一是&ldquo;代码&rdquo;，一定要简单，布局要合理。二是&ldquo;内容&rdquo;，一定要有原创，伪原创也是可以的。三是&ldquo;持续&rdquo;，这是一个持续性过程，一定要有耐心，SEO不是马上生效的。<br />
            <br />
            自从入了这一行，也交到了不少朋友，QQ群也不断的壮大起来，12345678(交流群 <span style="color:#FF0000;">已满员</span>)&nbsp; 280998843（技术群），群里的小伙伴们也很积极的帮助新朋友解决问题，如果你想加入我们，这个大家庭的门，永远给你敞开！另外微信群已于2018.4.13日开通（已满100，只接受群主邀请，可加我个人微信进群 。我的个人微信号 yangqq_1987）</p>
          <br />
          <h2>About my blog</h2>
          &nbsp;
          <p>服务器：阿里云服务器&nbsp;&nbsp;<a href="https://promotion.aliyun.com/ntms/act/ambassador/sharetouser.html?userCode=8smrzoqa&amp;productCode=vm" target="_blank"><span style="color:#FF0000;"><strong>前往阿里云官网购买&gt;&gt;</strong></span></a></p>
          <br />
          <p>备案号：蜀ICP备11002373号-1</p>
          <br />
          <p>程 序：PHP 帝国CMS7.5</p>

     </div>
  </main>
{% endblock %}

blog/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>首页_Deathfeeling个人博客 - 一个站在web前端设计之路的技术员个人博客网站</title>
    <meta name="keywords" content="个人博客,Deathfeeling个人博客,个人博客模板,Deathfeeling" />
    <meta name="description" content="Deathfeeling个人博客，是一个站在web前端设计之路的程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}


</head>
<body>
    <header class="header-navigation" id="header">
      <nav><div class="logo"><a href="">Deathfeeling's Blog</a></div>
        <h2 id="mnavh"><span class="navicon"></span></h2>
        <ul id="starlist">
          <li><a href="{% url 'myblog:index' %}">网站首页</a></li>
          <li><a href="{% url 'myblog:list' %}">我的文章</a></li>
          <li><a href="{% url 'myblog:column' %}">栏目页</a></li>
          <li><a href="{% url 'myblog:info' %}">内容页</a></li>
          <li><a href="{% url 'myblog:infopic' %}">欣赏</a></li>
          <li><a href="{% url 'myblog:gbook' %}">留言</a></li>
          <li><a href="{% url 'myblog:about' %}">关于我</a></li>
        </ul>
    </nav>
    </header>

<article>


    {% block aside %}
    {% endblock %}



    {% block main %}
    {% endblock %}


</article>

<footer>
  <p>Design by <a href="http://120.78.83.46" target="_blank">Deathfeeling个人博客</a> <a href="">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>

{% block sc %}
{% endblock %}

</body>
</html>

blog/templates/web/column.html
{% extends 'web/base.html' %}


{% block css %}
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
{% endblock %}

{% block js %}
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/web/js/modernizr.js"></script>
<![endif]-->
{% endblock %}



{% block aside %}
  <aside class="l_box">
 <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
          {% for column in columns %}
            <li><a href="{% url 'myblog:column' %}/?id={{ column.id }}">{{ column.name }}</a></li>
          {% endfor %}
        </ul>
    </div>
    <div class="tuijian">
      <h2>站长推荐</h2>
      <ul>
        <li><a href="">你是什么人便会遇上什么人</a></li>
        <li><a href="">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="">个人博客模板《绅士》后台管理</a></li>
        <li><a href="">你是什么人便会遇上什么人</a></li>
        <li><a href="">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="">个人博客模板《绅士》后台管理</a></li>
      </ul>
    </div>
     <div class="tuijian">
      <h2>点击排行</h2>
      <ul>
        <li><a href="">你是什么人便会遇上什么人</a></li>
        <li><a href="">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="">个人博客模板《绅士》后台管理</a></li>
        <li><a href="">你是什么人便会遇上什么人</a></li>
        <li><a href="">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="">个人博客模板《绅士》后台管理</a></li>
      </ul>
    </div>
<div class="cloud">
      <h2>标签云</h2>
      <ul>
        <a href="">陌上花开</a> <a href="">校园生活</a> <a href="">html5</a> <a href="">SumSung</a> <a href="">青春</a> <a href="">温暖</a> <a href="">阳光</a> <a href="">三星</a><a href="">索尼</a> <a href="">华维荣耀</a> <a href="">三星</a> <a href="">索尼</a>
      </ul>
    </div>
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/web/images/wx.jpg">
      </ul>
    </div>
  </aside>
{% endblock %}


{% block main %}
  <main class="r_box">
    {% for art in arts %}
      <li><i><a href=""><img src="/static/web/images/8.jpg"></a></i>
        <h3><a href="{% url 'myblog:info'%}/?id={{ art.id }}">{{ art.title }}</a></h3>
        <p>{{ art.content }}</p>
      </li>
    {% endfor %}

  </main>
{% endblock %}

blog/templates/web/gbook.html
{% extends 'web/base.html' %}

{% block css %}
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
{% endblock %}

{% block js %}
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/web/js/modernizr.js"></script>
<![endif]-->
{% endblock %}


{% block aside %}
  <aside class="l_box">
    <div class="about_me">
      <h2>关于我</h2>
      <ul>
        <i><img src="/static/web/images/4.jpg"></i>
        <p><b>Deathfeeling</b>，一个80后草根站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
      </ul>
    </div>
    <div class="wdxc">
      <h2>我的相册</h2>
      <ul>
        <li><a href=""><img src="/static/web/images/7.jpg"></a></li>
        <li><a href=""><img src="/static/web/images/8.jpg"></a></li>
        <li><a href=""><img src="/static/web/images/9.jpg"></a></li>
        <li><a href=""><img src="/static/web/images/10.jpg"></a></li>
        <li><a href=""><img src="/static/web/images/11.jpg"></a></li>
        <li><a href=""><img src="/static/web/images/12.jpg"></a></li>
      </ul>
    </div>
     <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
          {% for column in columns %}
            <li><a href="{% url 'myblog:column' %}/?id={{ column.id }}">{{ column.name }}</a></li>
          {% endfor %}
        </ul>
    </div>
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/web/images/wx.jpg">
      </ul>
    </div>
  </aside>
{% endblock %}

{% block main %}
  <main class="r_box">
<div class="gbook">
      <div class="fb">
        <ul>
          <p class="fbtime"><span> 2018-07-21 </span> 夜月归途</p>
          <p class="fbinfo">从青姐朋友圈分享的文章《我为什么要做个人网站》过来的，自习看了下你的网站非常不错，看的出来你一直在坚持!</p>
        </ul>
      </div>
      <div class="hf">
        <ul>
          <p class="zzhf"><font color="#FF0000">站长回复:</font>感谢捧场啊！看了你的网站，有两个月没更新了哦~</p>
        </ul>
      </div>
      <div class="fb">
        <ul>
          <p class="fbtime"><span> 2018-07-10 </span> 周宏</p>
          <p class="fbinfo">读《从今日起，我永久卸载今日头条》有感。正如作者所说，这个APP抓住了很多人性的特点，在简单、重复、爽这三点上做到了极致。但是我认为永久卸载这个想法比较荒诞，任何东西你只要有自控力，就能将它为我所用。曾经一度我也是刷头条根本停不下来</p>
        </ul>
      </div>
      <div class="hf">
        <ul>
          <p class="zzhf"><font color="#FF0000">站长回复:</font>嗯，我也是自制力有限，删除头条就是矫枉过正而已，这个因人而异，不强求他人，也不想标题党。</p>
        </ul>
      </div>
      <div class="fb">
        <ul>
          <p class="fbtime"><span> 2018-07-09 </span> 文颖</p>
          <p class="fbinfo">加油吖</p>
        </ul>
      </div>
      <div class="hf">
        <ul>
          <p class="zzhf"><font color="#FF0000">站长回复:</font>感谢第一条留言的支持！：）</p>
        </ul>
      </div>
      <div class="gbox">
        <form action="../../enews/index.php" method="post" name="form1" id="form1">
          <p> <strong>来说点儿什么吧...</strong></p>
          <p><span> 您的姓名:</span>
            <input name="name" type="text" id="name">
            *</p>
          <p><span>联系邮箱:</span>
            <input name="email" type="text" id="email">
            *</p>
          <p><span class="tnr">留言内容:</span>
            <textarea name="lytext" cols="60" rows="12" id="lytext"></textarea>
          </p>
          <p>
            <input type="submit" name="Submit3" value="提交">
            <input name="enews" type="hidden" id="enews" value="AddGbook">
          </p>
        </form>
      </div>
    </div>
  </main>
{% endblock %}

blog/templates/web/list.html
{% extends 'web/base.html' %}


{% block css %}
<link href="/static/web/css/base.css" rel="stylesheet">
<link href="/static/web/css/index.css" rel="stylesheet">
<link href="/static/web/css/m.css" rel="stylesheet">
{% endblock %}

{% block js %}
<script src="/static/web/js/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/web/js/hc-sticky.js"></script>
<script type="text/javascript" src="/static/web/js/comm.js"></script>
<!--[if lt IE 9]>
<script src="/static/web/js/modernizr.js"></script>
<![endif]-->
{% endblock %}



{% block aside %}
  <aside class="l_box">
 <div class="search">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="fenlei">
        <h2>文章分类</h2>
        <ul>
          {% for column in columns %}
            <li><a href="{% url 'myblog:column' %}/?id={{ column.id }}">{{ column.name }}</a></li>
          {% endfor %}
        </ul>
    </div>
    <div class="tuijian">
      <h2>站长推荐</h2>
      <ul>
        <li><a href="">你是什么人便会遇上什么人</a></li>
        <li><a href="">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="">个人博客模板《绅士》后台管理</a></li>
        <li><a href="">你是什么人便会遇上什么人</a></li>
        <li><a href="">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="">个人博客模板《绅士》后台管理</a></li>
      </ul>
    </div>
     <div class="tuijian">
      <h2>点击排行</h2>
      <ul>
        <li><a href="">你是什么人便会遇上什么人</a></li>
        <li><a href="">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="">个人博客模板《绅士》后台管理</a></li>
        <li><a href="">你是什么人便会遇上什么人</a></li>
        <li><a href="">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
        <li><a href="">第二届 优秀个人博客模板比赛参选活动</a></li>
        <li><a href="">个人博客模板《绅士》后台管理</a></li>
      </ul>
    </div>
<div class="cloud">
      <h2>标签云</h2>
      <ul>
        <a href="">陌上花开</a> <a href="">校园生活</a> <a href="">html5</a> <a href="">SumSung</a> <a href="">青春</a> <a href="">温暖</a> <a href="">阳光</a> <a href="">三星</a><a href="">索尼</a> <a href="">华维荣耀</a> <a href="">三星</a> <a href="">索尼</a>
      </ul>
    </div>
    <div class="guanzhu">
      <h2>关注我 么么哒</h2>
      <ul>
        <img src="/static/web/images/wx.jpg">
      </ul>
    </div>
  </aside>
{% endblock %}


{% block main %}
  <main class="r_box">
    {% for art in arts %}
      <li><i><a href=""><img src="/static/web/images/4.jpg"></a></i>
        <h3><a href="{% url 'myblog:info'%}/?id={{ art.id }}">{{ art.title }}</a></h3>
        <p>{{ art.content }}</p>
      </li>
    {% endfor %}
    <div class="pagelist">
      {% if arts.has_previous %}<a class="allpage" href="{% url 'myblog:list' %}?page={{ arts.previous_page_number }}"><b>上一页</b></a>{% endif %}&nbsp;&nbsp;
      {% for i in arts.paginator.page_range %}
          <a class="curPage" href="{% url 'myblog:list' %}?page={{ i }}">{{ i }}</a>
      {% endfor %}
      {% if arts.has_next %}<a class="allpage" href="{% url 'myblog:list' %}?page={{ arts.next_page_number }}"><b>下一页</b></a>{% endif %}&nbsp;&nbsp;
    </div>
  </main>
{% endblock %}